services:
  - type: web
    name: suibeacon-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SUI_NETWORK
        sync: false
      - key: SUI_MNEMONIC
        sync: false
      - key: XAI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false